// Generated by CoffeeScript 1.10.0
var disabler, load, windowcontroller;

windowcontroller = function(what) {
  switch (what) {
    case "lml":
      $("#lml-content").collapse("show");
      return $("#code-content").collapse("hide");
    case "code":
      $("#lml-content").collapse("hide");
      return $("#code-content").collapse("show");
  }
};

load = function() {
  var currentIndex, langs, randomIndex, temporaryValue;
  loadparams();
  Mousetrap.bind('s e x y', function() {
    return sexydown;
  });
  langs = ["Markdown.", "Textile.", "C#.", "JavaScript.", "Perl.", "Java.", "Python.", "Ruby.", "Rust.", "R.", "PHP.", "HTML.", "CSS.", "Bash.", "CoffeeScript.", "SQL.", "Objective-C.", "C++.", "Apache.", "HTTP.", "JSON.", "FORTRAN.", "Processing.", "Brainf**k.", "Smalltalk.", "Cloqure.", "Dart.", "Go.", "VB.NET.", "Swift.", "Matlab.", "Haml.", "DOS .bat.", "Scala.", "Haskell.", "Lua.", "TeX.", "F#.", "Django.", "Lisp.", "AutoHotkey.", "LESS.", "SASS."];
  currentIndex = langs.length;
  while (0 !== currentIndex) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;
    temporaryValue = langs[currentIndex];
    langs[currentIndex] = langs[randomIndex];
    langs[randomIndex] = temporaryValue;
  }
  return $('#titlespan').typed({
    strings: langs,
    typeSpeed: 0,
    startDelay: 3000,
    backSpeed: 0,
    backDelay: 3000,
    loop: true,
    loopCount: false,
    showCursor: true,
    cursorChar: '|'
  });
};

disabler = function(id1, id2, s) {
  var disable1, disable2, sender;
  disable1 = document.getElementById(id1);
  disable2 = document.getElementById(id2);
  sender = document.getElementById(s);
  if (sender.value !== '') {
    $(disable1).attr('disabled', 'disabled');
    $(disable2).attr('disabled', 'disabled');
    $(disable1).val('');
    $(disable2).val('');
  } else {
    $(disable1).removeAttr('disabled');
    $(disable2).removeAttr('disabled');
  }
};
